# Generated by Django 4.1.7 on 2023-03-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tittle',
            new_name='Bookname',
        ),
        migrations.AddField(
            model_name='article',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
